apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
controlPlaneEndpoint: 1.2.3.4.5.6.7.8.9.0:6443
kubernetesVersion: "v1.12.0"
networking:
  podSubnet: "10.100.0.1/24" # CIRD
apiServer:
  extraArgs:
    enable-admission-plugins: PodSecurityPolicy
