apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
bootstrapTokens:
  - token: "abcdef.0123456789abcdef" # Kubeadm TOKEN
    description: "default kubeadm bootstrap token"
localAPIEndpoint:
  advertiseAddress: 1.2.3.4.5.6.7.8.9.0
  bindPort: 6443
