apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
bootstrapTokens:
- token: "abcdef.0123456789abcdef" # Kubeadm TOKEN
  description: "default kubeadm bootstrap token"
localAPIEndpoint:
  advertiseAddress: "10.100.0.1" # MASTER_PUBLIC_IP
  bindPort: 6443
nodeRegistration:
  name: "ec2-10-100-0-1"
  criSocket: "/var/run/dockershim.sock"
  kubeletExtraArgs:
    cgroup-driver: "cgroupfs"
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
# controlPlaneEndpoint: ${K8S_API_ENDPOINT_INTERNAL}:6443
kubernetesVersion: "v1.12.0" # K8_VERSION_LONG
networking:
  podSubnet: "10.100.0.1/24" # CIRD
