kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-specific-ingress
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: hello-world
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: hello-client
