- hosts: masters
  become: yes
  tasks:
   - name: Create Istio directory
     file:
       path: $HOME/istio
       state: directory

   - name: Create Istio namespace
     shell: kubectl create namespace istio-system >> namespace.log
     args:
       chdir: $HOME/istio
       creates: namespace.log

   - name: Download Istio
     get_url:
       url: https://git.io/getLatestIstio
       dest: $HOME/istio/getLatestIstio.sh
       mode: '770'

   - name: Run getLatestIstio.sh
     shell: ISTIO_VERSION=1.1.2 ./getLatestIstio.sh
     register: get_istio
     args:
       chdir: $HOME/istio

   - name: Install Istio (Demo profile)
     when: get_istio is succeeded and istio_profile == "DEMO"
     shell: |
        helm template install/kubernetes/helm/istio-init --name istio-init --namespace istio-system | kubectl apply -f - &&\
        sleep 30 &&\
        helm template install/kubernetes/helm/istio --name istio --namespace istio-system --values install/kubernetes/helm/istio/values-istio-demo.yaml | kubectl apply -f - &&\
        sleep 30
     register: install_istio
     args:
       chdir: $HOME/istio/istio-1.1.2

   - name: Install Istio (Production profile)
     when: get_istio is succeeded and istio_profile == "PROD"
     shell: |
        helm template install/kubernetes/helm/istio-init --name istio-init --namespace istio-system | kubectl apply -f - &&\
        sleep 30 &&\
        helm template install/kubernetes/helm/istio --name istio --namespace istio-system | kubectl apply -f - &&\
        sleep 30
     register: install_istio
     args:
       chdir: $HOME/istio/istio-1.1.2

   - name: Install Istio (Demo-auth profile)
     when: get_istio is succeeded and istio_profile == "DEMOAUTH"
     shell: |
        helm template install/kubernetes/helm/istio-init --name istio-init --namespace istio-system | kubectl apply -f - &&\
        sleep 30 &&\
        helm template install/kubernetes/helm/istio --name istio --namespace istio-system --values install/kubernetes/helm/istio/values-istio-demo-auth.yaml | kubectl apply -f - &&\
        sleep 30
     register: install_istio
     args:
       chdir: $HOME/istio/istio-1.1.2

   - name: Add istio-injection label to default namespace
     when: install_istio is succeeded
     shell: kubectl label namespace default istio-injection=enabled
