- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: initialize the cluster
      shell: "kubeadm init --apiserver-advertise-address {{ master_public_ip }} --pod-network-cidr={{ cidr }} --kubernetes-version={{ k8_version }} >> kubeadm-init.log"
      args:
        chdir: $HOME
        creates: kubeadm-init.log

    - name: create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: get join command
      shell: "kubeadm token create --print-join-command"
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: workers
  become: yes
  tasks:
  - name: join cluster
    shell: "{{ hostvars['master'].join_command }} >> kubeadm-join.log"
    args:
      chdir: $HOME
      creates: kubeadm-join.log
