- hosts: master
  become: yes
  tasks:
   - name: Install unzip
     apt:
       name: unzip
       state: present
       update_cache: true

   - name: Create a non-privileged Vault system user
     user:
       name: vault
       system: true
       home: /etc/vault.d
       shell: /bin/false

   - name: Create Vault directory for installation
     file:
       path: $HOME/hashicorp-vault
       state: directory

   - name: Create Vault storage directory under /var/lib/
     file:
       path: /var/lib/vault
       state: directory
       owner: vault

   - name: Create Vault config dir under /etc/
     file:
       path: /etc/vault.d
       state: directory

   - name: Download Vault
     get_url:
       url: https://releases.hashicorp.com/vault/1.1.1/vault_1.1.1_linux_amd64.zip
       dest: $HOME/hashicorp-vault/vault.zip
       mode: '770'

   - name: Extract archive contents
     unarchive:
      src: $HOME/hashicorp-vault/vault.zip
      dest: $HOME/hashicorp-vault/
      remote_src: yes

   - name: Copy Vault into /bin
     copy:
       src: $HOME/hashicorp-vault/vault
       dest: /usr/local/bin/
       mode: '770'
       owner: vault
       remote_src: yes

   - name: Allow Vault to use mlock syscall without root
     shell: setcap cap_ipc_lock=+ep /usr/local/bin/vault

   - name: Add Vault config
     copy:
       dest: /etc/vault.d/vault.hcl
       content: |
         ui = true

         storage "file" {
             path    = "/var/lib/vault"
         }

         listener "tcp" {
            address     = "127.0.0.1:8200"
            tls_disable = 1
         }

   - name: Add systemd config for Vault (runs vault as root user, not vault)
     copy:
      dest: /etc/systemd/system/vault.service
      content: |
        [Unit]
        Description="HashiCorp Vault - A tool for managing secrets"
        Documentation=https://www.vaultproject.io/docs/
        Requires=network-online.target
        After=network-online.target
        ConditionFileNotEmpty=/etc/vault.d/vault.hcl

        [Service]
        User=vault
        Group=vault
        ProtectSystem=full
        ProtectHome=read-only
        PrivateTmp=yes
        PrivateDevices=yes
        SecureBits=keep-caps
        AmbientCapabilities=CAP_IPC_LOCK
        Capabilities=CAP_IPC_LOCK+ep
        CapabilityBoundingSet=CAP_SYSLOG CAP_IPC_LOCK
        NoNewPrivileges=yes
        ExecStart=/usr/local/bin/vault server -config=/etc/vault.d/vault.hcl
        ExecReload=/bin/kill --signal HUP $MAINPID
        KillMode=process
        KillSignal=SIGINT
        Restart=on-failure
        RestartSec=5
        TimeoutStopSec=30
        StartLimitInterval=60
        StartLimitBurst=3
        LimitNOFILE=65536

        [Install]
        WantedBy=multi-user.target

   - name: Fix permissions
     shell: |
        chown --recursive vault:vault /etc/vault.d &&\
        chmod 640 /etc/vault.d/vault.hcl

   - name: Start Vault server
     shell: |
        systemctl enable vault &&\
        systemctl start vault

   - name: Initalize Vault
     shell: |
        vault operator init -address http://127.0.0.1:8200/ >> vault-operator-init.log
     args:
       chdir: $HOME/hashicorp-vault
       creates: vault-operator-init.log
