- hosts: master
  become: yes
  tasks:
   - name: Install unzip
     apt:
       name: unzip
       state: present
       update_cache: true

   - name: Create Vault directory
     file:
       path: $HOME/hashicorp-vault
       state: directory

   - name: Download Vault
     get_url:
       url: https://releases.hashicorp.com/vault/1.1.1/vault_1.1.1_linux_amd64.zip
       dest: $HOME/hashicorp-vault/vault.zip
       mode: '770'

   - name: Extract archive contents
     unarchive:
      src: $HOME/hashicorp-vault/vault.zip
      dest: $HOME/hashicorp-vault/
      remote_src: yes

   - name: Copy Vault into /bin
     copy:
       src: $HOME/hashicorp-vault/vault
       dest: /bin/
       mode: '770'
       remote_src: yes

   - name: Create Vault config dir under /etc
     file:
       path: /etc/vault.d
       state: directory

   - name: Add Vault config
     copy:
       dest: /etc/vault.d/vault.hcl
       content: |
         ui = true

         storage "file" {
             path    = "root/hashicorp-vault/vault-data"
         }

         listener "tcp" {
            address     = "127.0.0.1:8200"
            tls_disable = 1
         }

   - name: Add systemd config for Vault (runs vault as root user, not vault)
     copy:
      dest: /etc/systemd/system/vault.service
      content: |
        [Unit]
        Description="HashiCorp Vault - A tool for managing secrets"
        Documentation=https://www.vaultproject.io/docs/
        Requires=network-online.target
        After=network-online.target
        ConditionFileNotEmpty=/etc/vault.d/vault.hcl

        [Service]
        User=root
        Group=root
        ProtectSystem=full
        ProtectHome=read-only
        PrivateTmp=yes
        PrivateDevices=yes
        SecureBits=keep-caps
        AmbientCapabilities=CAP_IPC_LOCK
        Capabilities=CAP_IPC_LOCK+ep
        CapabilityBoundingSet=CAP_SYSLOG CAP_IPC_LOCK
        NoNewPrivileges=yes
        ExecStart=/usr/local/bin/vault server -config=/etc/vault.d/vault.hcl
        ExecReload=/bin/kill --signal HUP $MAINPID
        KillMode=process
        KillSignal=SIGINT
        Restart=on-failure
        RestartSec=5
        TimeoutStopSec=30
        StartLimitInterval=60
        StartLimitBurst=3
        LimitNOFILE=65536

        [Install]
        WantedBy=multi-user.target

   - name: Start Vault server
     shell: |
        systemctl enable vault &&\
        systemctl start vault
