- hosts: all
  become: yes
  vars:
    crio_version: 1.13
  tasks:
    - name: Add Overlay Linux Module
      modprobe:
        name: overlay
        state: present

    - name: Add Bridge-netfilter Linux Module
      modprobe:
        name: br_netfilter
        state: present

    - name: add CRI-O's APT repository
      apt_repository:
      repo: ppa:projectatomic/ppa
      state: present

    - name: install CRI-O
      apt:
      name: cri-o-{{ crio_version }}
      state: present
      update_cache: true
