# BUG NOTICE:
#   Due to a bug https://github.com/istio/istio/issues/9504 Istio-proxy
#   start when containerPort is set
# UPDATE ON BUG:
#   No! Instead verify that Istio's requirements on pods are satisfied:
#   https://istio.io/docs/setup/kubernetes/prepare/requirements/
#
#   In our case each pod must always
#     * be associated with a Kubernetes Service
#     * Have both protocol, port and targetPort defined in the Service
#     * Have containerPort defined in the deployment

apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
  namespace: default
  labels:
    app: hello-world
spec:
  ports:
    - port: 80
      name: http
      targetPort: 3000
  selector:
    app: hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  namespace: default
  labels:
    app: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: chrismessiah/hello-world:latest
        ports:
        - containerPort: 3000
